create table bank (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table bank_transaction (amount float(23), bank_id bigint, deposit_id bigint, id bigint not null auto_increment, transaction_date datetime(6), user_id bigint, vendor_id bigint, description varchar(255), payee varchar(255), transaction_type varchar(255), primary key (id)) engine=InnoDB;
create table bill (fixed_payment_amount float(23), expense_id bigint, id bigint not null auto_increment, user_id bigint, fixed_payments varchar(255), payment_schedule varchar(255), primary key (id)) engine=InnoDB;
create table budgeted_transaction (paid bit not null, transaction_amount float(23) not null, budget_entry_id bigint, due_date datetime(6), id bigint not null auto_increment, user_id bigint, primary key (id)) engine=InnoDB;
create table budget_entry (scheduled_amount float(23), bill_id bigint, deposit_id bigint, end_date datetime(6), id bigint not null auto_increment, start_date datetime(6), user_id bigint, frequency varchar(255), note varchar(255), scheduled_type varchar(255), primary key (id)) engine=InnoDB;
create table deposit (deposit_category_id bigint, id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table deposit_category (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table deposit_matching_rule (execution_order integer, deposit_id bigint, id bigint not null auto_increment, user_id bigint, deposit_like_criteria varchar(255), deposit_regex_criteria varchar(255), primary key (id)) engine=InnoDB;
create table expense (expense_category_id bigint, id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table expense_category (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table login_event (id bigint not null auto_increment, login_date datetime(6), user_account_id bigint, ip_address varchar(255), primary key (id)) engine=InnoDB;
create table shopping_item (id bigint not null auto_increment, shopping_item_category_id bigint, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table shopping_item_category (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table shopping_item_purchase (amount float(23), quantity integer, total_amount float(23), bank_transaction_id bigint, id bigint not null auto_increment, shopping_item_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_account (admin_flag bit not null, id bigint not null auto_increment, last_login_date datetime(6), email_address varchar(255), encrypted_password varchar(255), first_name varchar(255), last_login_ip_address varchar(255), last_name varchar(255), user_name varchar(255), user_password varchar(255), primary key (id)) engine=InnoDB;
create table vendor (expense_id bigint, id bigint not null auto_increment, user_id bigint, desription varchar(255), primary key (id)) engine=InnoDB;
create table vendor_account (id bigint not null auto_increment, user_id bigint, vendor_id bigint, user_name varchar(255), user_password varchar(255), vendor_website varchar(255), primary key (id)) engine=InnoDB;
create table vendor_matching_rule (execution_order integer, id bigint not null auto_increment, user_id bigint, vendor_id bigint, vendor_like_criteria varchar(255), vendor_regex_criteria varchar(255), primary key (id)) engine=InnoDB;
alter table bank add constraint FKen1pw9kxo5lmtio7dspfdfr8w foreign key (user_id) references user_account (id);
alter table bank_transaction add constraint FKmxomsvva422ml4eyehbkru5hb foreign key (bank_id) references bank (id);
alter table bank_transaction add constraint FKdg8wts9rpw56heo6tllvq1me5 foreign key (deposit_id) references deposit (id);
alter table bank_transaction add constraint FKlo3oggailiwqymxaxy2jgmlww foreign key (user_id) references user_account (id);
alter table bank_transaction add constraint FK6r7vl1hn144ikrlsx7mnvh2f8 foreign key (vendor_id) references vendor (id);
alter table bill add constraint FKoxdd62gjaa69f8p83m7lktjti foreign key (expense_id) references expense (id);
alter table bill add constraint FK1pneh41x6updi26pc2mn1gutw foreign key (user_id) references user_account (id);
alter table budgeted_transaction add constraint FK7depx381s00we6kqf3uj03xd3 foreign key (budget_entry_id) references budget_entry (id);
alter table budgeted_transaction add constraint FKfqcktthsiirnur1o3w759sg9m foreign key (user_id) references user_account (id);
alter table budget_entry add constraint FKnxc10ou0682nv4tuje0w2n2r8 foreign key (bill_id) references bill (id);
alter table budget_entry add constraint FKn51e6tbp2sos7f8jp6thsd805 foreign key (deposit_id) references deposit (id);
alter table budget_entry add constraint FKhllkk5b9i12x37h0dv9j01hmj foreign key (user_id) references user_account (id);
alter table deposit add constraint FK5ww2ssmqalcmov4p184oxgo8s foreign key (deposit_category_id) references deposit_category (id);
alter table deposit add constraint FKiqmbhrcmqd22c3m9rh3x0a8ej foreign key (user_id) references user_account (id);
alter table deposit_category add constraint FKtfi85lidskp1m2r6bdrg2ja10 foreign key (user_id) references user_account (id);
alter table deposit_matching_rule add constraint FKp8lplw6y9y5a3c1vr16xjdjeg foreign key (deposit_id) references deposit (id);
alter table deposit_matching_rule add constraint FKnvwulyrydt3o00ete0ta61r4q foreign key (user_id) references user_account (id);
alter table expense add constraint FKhuho44ssbmqywb3nfmm4ljfmk foreign key (expense_category_id) references expense_category (id);
alter table expense add constraint FK9f8o09c45pnmpjavji04tf16t foreign key (user_id) references user_account (id);
alter table expense_category add constraint FK3srsl5kxlcpsp26baer8ljt43 foreign key (user_id) references user_account (id);
alter table login_event add constraint FK4futx8tgf58e10280a4b5xjqc foreign key (user_account_id) references user_account (id);
alter table shopping_item add constraint FK10akpu162pkovc0d8pyg56842 foreign key (shopping_item_category_id) references shopping_item_category (id);
alter table shopping_item add constraint FKp67lls4c14lu5puu2nv6n66bu foreign key (user_id) references user_account (id);
alter table shopping_item_category add constraint FK5ablf6e7o7ip5jggdhmkbyq8e foreign key (user_id) references user_account (id);
alter table shopping_item_purchase add constraint FKofp5u2hcvuftkw9ju4iq0vlak foreign key (bank_transaction_id) references bank_transaction (id);
alter table shopping_item_purchase add constraint FKffhmabmctisvmldp1h2awg0d2 foreign key (shopping_item_id) references shopping_item (id);
alter table shopping_item_purchase add constraint FKckregby72r2c6lsqbc4ye52hq foreign key (user_id) references user_account (id);
alter table vendor add constraint FKr40m4wadqi8gub9xg0a2g8qbh foreign key (expense_id) references expense (id);
alter table vendor add constraint FKojy4m8vaj6mu4xx0lvku6etso foreign key (user_id) references user_account (id);
alter table vendor_account add constraint FK4g9lxc9craedtw1guu90jvy9q foreign key (user_id) references user_account (id);
alter table vendor_account add constraint FKdjbbf2x95i8emaru1o8egfjw5 foreign key (vendor_id) references vendor (id);
alter table vendor_matching_rule add constraint FKbl7fp16sc21ds62vpcac8v6rs foreign key (user_id) references user_account (id);
alter table vendor_matching_rule add constraint FKjc6c9w1db49i7rta2ho83grq2 foreign key (vendor_id) references vendor (id);
create table bank (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table bank_transaction (amount float(23), bank_id bigint, deposit_id bigint, id bigint not null auto_increment, transaction_date datetime(6), user_id bigint, vendor_id bigint, description varchar(255), payee varchar(255), transaction_type varchar(255), primary key (id)) engine=InnoDB;
create table bill (fixed_payment_amount float(23), expense_id bigint, id bigint not null auto_increment, user_id bigint, fixed_payments varchar(255), payment_schedule varchar(255), primary key (id)) engine=InnoDB;
create table budgeted_transaction (paid bit not null, transaction_amount float(23) not null, budget_entry_id bigint, due_date datetime(6), id bigint not null auto_increment, user_id bigint, primary key (id)) engine=InnoDB;
create table budget_entry (scheduled_amount float(23), bill_id bigint, deposit_id bigint, end_date datetime(6), id bigint not null auto_increment, start_date datetime(6), user_id bigint, frequency varchar(255), note varchar(255), scheduled_type varchar(255), primary key (id)) engine=InnoDB;
create table deposit (deposit_category_id bigint, id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table deposit_category (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table deposit_matching_rule (execution_order integer, deposit_id bigint, id bigint not null auto_increment, user_id bigint, deposit_like_criteria varchar(255), deposit_regex_criteria varchar(255), primary key (id)) engine=InnoDB;
create table expense (expense_category_id bigint, id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table expense_category (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table login_event (id bigint not null auto_increment, login_date datetime(6), user_account_id bigint, ip_address varchar(255), primary key (id)) engine=InnoDB;
create table shopping_item (id bigint not null auto_increment, shopping_item_category_id bigint, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table shopping_item_category (id bigint not null auto_increment, user_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table shopping_item_purchase (amount float(23), quantity integer, total_amount float(23), bank_transaction_id bigint, id bigint not null auto_increment, shopping_item_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_account (admin_flag bit not null, id bigint not null auto_increment, last_login_date datetime(6), email_address varchar(255), encrypted_password varchar(255), first_name varchar(255), last_login_ip_address varchar(255), last_name varchar(255), user_name varchar(255), user_password varchar(255), primary key (id)) engine=InnoDB;
create table vendor (expense_id bigint, id bigint not null auto_increment, user_id bigint, desription varchar(255), primary key (id)) engine=InnoDB;
create table vendor_account (id bigint not null auto_increment, user_id bigint, vendor_id bigint, user_name varchar(255), user_password varchar(255), vendor_website varchar(255), primary key (id)) engine=InnoDB;
create table vendor_matching_rule (execution_order integer, id bigint not null auto_increment, user_id bigint, vendor_id bigint, vendor_like_criteria varchar(255), vendor_regex_criteria varchar(255), primary key (id)) engine=InnoDB;
alter table bank add constraint FKen1pw9kxo5lmtio7dspfdfr8w foreign key (user_id) references user_account (id);
alter table bank_transaction add constraint FKmxomsvva422ml4eyehbkru5hb foreign key (bank_id) references bank (id);
alter table bank_transaction add constraint FKdg8wts9rpw56heo6tllvq1me5 foreign key (deposit_id) references deposit (id);
alter table bank_transaction add constraint FKlo3oggailiwqymxaxy2jgmlww foreign key (user_id) references user_account (id);
alter table bank_transaction add constraint FK6r7vl1hn144ikrlsx7mnvh2f8 foreign key (vendor_id) references vendor (id);
alter table bill add constraint FKoxdd62gjaa69f8p83m7lktjti foreign key (expense_id) references expense (id);
alter table bill add constraint FK1pneh41x6updi26pc2mn1gutw foreign key (user_id) references user_account (id);
alter table budgeted_transaction add constraint FK7depx381s00we6kqf3uj03xd3 foreign key (budget_entry_id) references budget_entry (id);
alter table budgeted_transaction add constraint FKfqcktthsiirnur1o3w759sg9m foreign key (user_id) references user_account (id);
alter table budget_entry add constraint FKnxc10ou0682nv4tuje0w2n2r8 foreign key (bill_id) references bill (id);
alter table budget_entry add constraint FKn51e6tbp2sos7f8jp6thsd805 foreign key (deposit_id) references deposit (id);
alter table budget_entry add constraint FKhllkk5b9i12x37h0dv9j01hmj foreign key (user_id) references user_account (id);
alter table deposit add constraint FK5ww2ssmqalcmov4p184oxgo8s foreign key (deposit_category_id) references deposit_category (id);
alter table deposit add constraint FKiqmbhrcmqd22c3m9rh3x0a8ej foreign key (user_id) references user_account (id);
alter table deposit_category add constraint FKtfi85lidskp1m2r6bdrg2ja10 foreign key (user_id) references user_account (id);
alter table deposit_matching_rule add constraint FKp8lplw6y9y5a3c1vr16xjdjeg foreign key (deposit_id) references deposit (id);
alter table deposit_matching_rule add constraint FKnvwulyrydt3o00ete0ta61r4q foreign key (user_id) references user_account (id);
alter table expense add constraint FKhuho44ssbmqywb3nfmm4ljfmk foreign key (expense_category_id) references expense_category (id);
alter table expense add constraint FK9f8o09c45pnmpjavji04tf16t foreign key (user_id) references user_account (id);
alter table expense_category add constraint FK3srsl5kxlcpsp26baer8ljt43 foreign key (user_id) references user_account (id);
alter table login_event add constraint FK4futx8tgf58e10280a4b5xjqc foreign key (user_account_id) references user_account (id);
alter table shopping_item add constraint FK10akpu162pkovc0d8pyg56842 foreign key (shopping_item_category_id) references shopping_item_category (id);
alter table shopping_item add constraint FKp67lls4c14lu5puu2nv6n66bu foreign key (user_id) references user_account (id);
alter table shopping_item_category add constraint FK5ablf6e7o7ip5jggdhmkbyq8e foreign key (user_id) references user_account (id);
alter table shopping_item_purchase add constraint FKofp5u2hcvuftkw9ju4iq0vlak foreign key (bank_transaction_id) references bank_transaction (id);
alter table shopping_item_purchase add constraint FKffhmabmctisvmldp1h2awg0d2 foreign key (shopping_item_id) references shopping_item (id);
alter table shopping_item_purchase add constraint FKckregby72r2c6lsqbc4ye52hq foreign key (user_id) references user_account (id);
alter table vendor add constraint FKr40m4wadqi8gub9xg0a2g8qbh foreign key (expense_id) references expense (id);
alter table vendor add constraint FKojy4m8vaj6mu4xx0lvku6etso foreign key (user_id) references user_account (id);
alter table vendor_account add constraint FK4g9lxc9craedtw1guu90jvy9q foreign key (user_id) references user_account (id);
alter table vendor_account add constraint FKdjbbf2x95i8emaru1o8egfjw5 foreign key (vendor_id) references vendor (id);
alter table vendor_matching_rule add constraint FKbl7fp16sc21ds62vpcac8v6rs foreign key (user_id) references user_account (id);
alter table vendor_matching_rule add constraint FKjc6c9w1db49i7rta2ho83grq2 foreign key (vendor_id) references vendor (id);
